# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b4e81e1060ff0f5a1ba650fd68aa588b76c460eb2270d16655aedcd2ec23224409bf0d9b52051052c1d49ae9bc056640716af5fff421bc91548bdc219b76d748

test:
  secret_key_base: 7662d38efe870c142726941dea4b032da28cea0d790010c6420f0dbda75cff198ba2dab604a4d0327a9552d899c5a29cf27253d8c90fd7aca9d5068a9d008f80

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
